/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The UserLogin model module.
 * @module model/UserLogin
 * @version 1.0.0
 */
export default class UserLogin {
  /**
   * Constructs a new <code>UserLogin</code>.
   * @alias module:model/UserLogin
   * @class
   * @param username {String} 
   * @param password {String} 
   */
  constructor(username, password) {
    this.username = username;
    this.password = password;
  }

  /**
   * Constructs a <code>UserLogin</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserLogin} obj Optional instance to populate.
   * @return {module:model/UserLogin} The populated <code>UserLogin</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserLogin();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} username
 */
UserLogin.prototype.username = undefined;

/**
 * @member {String} password
 */
UserLogin.prototype.password = undefined;

