/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The WorkoutUpdate model module.
 * @module model/WorkoutUpdate
 * @version 1.0.0
 */
export default class WorkoutUpdate {
  /**
   * Constructs a new <code>WorkoutUpdate</code>.
   * @alias module:model/WorkoutUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WorkoutUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkoutUpdate} obj Optional instance to populate.
   * @return {module:model/WorkoutUpdate} The populated <code>WorkoutUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkoutUpdate();
      if (data.hasOwnProperty('exerciseType'))
        obj.exerciseType = ApiClient.convertToType(data['exerciseType'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('distance'))
        obj.distance = ApiClient.convertToType(data['distance'], 'Number');
      if (data.hasOwnProperty('sets'))
        obj.sets = ApiClient.convertToType(data['sets'], 'Number');
      if (data.hasOwnProperty('reps'))
        obj.reps = ApiClient.convertToType(data['reps'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} exerciseType
 */
WorkoutUpdate.prototype.exerciseType = undefined;

/**
 * @member {Number} duration
 */
WorkoutUpdate.prototype.duration = undefined;

/**
 * @member {Number} distance
 */
WorkoutUpdate.prototype.distance = undefined;

/**
 * @member {Number} sets
 */
WorkoutUpdate.prototype.sets = undefined;

/**
 * @member {Number} reps
 */
WorkoutUpdate.prototype.reps = undefined;

