/**
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("apiUsersGet", () => {
    return expect(instance.apiUsersGet({})).resolves.toBe(null)
  })
  test("apiUsersPost", () => {
    const body: api.UserLogin = undefined
    return expect(instance.apiUsersPost(body, {})).resolves.toBe(null)
  })
  test("apiUsersPut", () => {
    const body: api.UserProfileUpdate = undefined
    return expect(instance.apiUsersPut(body, {})).resolves.toBe(null)
  })
  test("apiWorkoutsGet", () => {
    return expect(instance.apiWorkoutsGet({})).resolves.toBe(null)
  })
  test("apiWorkoutsPost", () => {
    const body: api.WorkoutLog = undefined
    return expect(instance.apiWorkoutsPost(body, {})).resolves.toBe(null)
  })
  test("apiWorkoutsPut", () => {
    const body: api.WorkoutUpdate = undefined
    const workoutId: string = "workoutId_example"
    return expect(instance.apiWorkoutsPut(body, workoutId, {})).resolves.toBe(null)
  })
  test("apiWorkoutsWorkoutIdDelete", () => {
    const workoutId: string = "workoutId_example"
    return expect(instance.apiWorkoutsWorkoutIdDelete(workoutId, {})).resolves.toBe(null)
  })
  test("apiWorkoutsWorkoutIdGet", () => {
    const workoutId: string = "workoutId_example"
    return expect(instance.apiWorkoutsWorkoutIdGet(workoutId, {})).resolves.toBe(null)
  })
})

