/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import UserLogin from './model/UserLogin';
import UserProfileUpdate from './model/UserProfileUpdate';
import UserRegistration from './model/UserRegistration';
import WorkoutLog from './model/WorkoutLog';
import WorkoutUpdate from './model/WorkoutUpdate';
import DefaultApi from './api/DefaultApi';

/**
* API_documentation_for_the_Fitness_Tracker_Web_Application.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FitnessTrackerApi = require('index'); // See note below*.
* var xxxSvc = new FitnessTrackerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FitnessTrackerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FitnessTrackerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FitnessTrackerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The UserLogin model constructor.
     * @property {module:model/UserLogin}
     */
    UserLogin,

    /**
     * The UserProfileUpdate model constructor.
     * @property {module:model/UserProfileUpdate}
     */
    UserProfileUpdate,

    /**
     * The UserRegistration model constructor.
     * @property {module:model/UserRegistration}
     */
    UserRegistration,

    /**
     * The WorkoutLog model constructor.
     * @property {module:model/WorkoutLog}
     */
    WorkoutLog,

    /**
     * The WorkoutUpdate model constructor.
     * @property {module:model/WorkoutUpdate}
     */
    WorkoutUpdate,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
