/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitnessTrackerApi);
  }
}(this, function(expect, FitnessTrackerApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FitnessTrackerApi.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('apiUsersGet', function() {
        it('should call apiUsersGet successfully', function(done) {
          // TODO: uncomment apiUsersGet call
          /*

          instance.apiUsersGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiUsersPost', function() {
        it('should call apiUsersPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiUsersPost call
          /*

          instance.apiUsersPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiUsersPut', function() {
        it('should call apiUsersPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiUsersPut call
          /*

          instance.apiUsersPut(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWorkoutsGet', function() {
        it('should call apiWorkoutsGet successfully', function(done) {
          // TODO: uncomment apiWorkoutsGet call
          /*

          instance.apiWorkoutsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWorkoutsPost', function() {
        it('should call apiWorkoutsPost successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWorkoutsPost call
          /*

          instance.apiWorkoutsPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWorkoutsPut', function() {
        it('should call apiWorkoutsPut successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWorkoutsPut call
          /*

          instance.apiWorkoutsPut(body, workoutId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWorkoutsWorkoutIdDelete', function() {
        it('should call apiWorkoutsWorkoutIdDelete successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWorkoutsWorkoutIdDelete call
          /*

          instance.apiWorkoutsWorkoutIdDelete(workoutId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('apiWorkoutsWorkoutIdGet', function() {
        it('should call apiWorkoutsWorkoutIdGet successfully', function(done) {
          // TODO: uncomment, update parameter values for apiWorkoutsWorkoutIdGet call
          /*

          instance.apiWorkoutsWorkoutIdGet(workoutId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
