/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The WorkoutLog model module.
 * @module model/WorkoutLog
 * @version 1.0.0
 */
export default class WorkoutLog {
  /**
   * Constructs a new <code>WorkoutLog</code>.
   * @alias module:model/WorkoutLog
   * @class
   * @param exerciseType {String} 
   * @param duration {Number} 
   */
  constructor(exerciseType, duration) {
    this.exerciseType = exerciseType;
    this.duration = duration;
  }

  /**
   * Constructs a <code>WorkoutLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WorkoutLog} obj Optional instance to populate.
   * @return {module:model/WorkoutLog} The populated <code>WorkoutLog</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WorkoutLog();
      if (data.hasOwnProperty('exerciseType'))
        obj.exerciseType = ApiClient.convertToType(data['exerciseType'], 'String');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('distance'))
        obj.distance = ApiClient.convertToType(data['distance'], 'Number');
      if (data.hasOwnProperty('sets'))
        obj.sets = ApiClient.convertToType(data['sets'], 'Number');
      if (data.hasOwnProperty('reps'))
        obj.reps = ApiClient.convertToType(data['reps'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} exerciseType
 */
WorkoutLog.prototype.exerciseType = undefined;

/**
 * @member {Number} duration
 */
WorkoutLog.prototype.duration = undefined;

/**
 * @member {Number} distance
 */
WorkoutLog.prototype.distance = undefined;

/**
 * @member {Number} sets
 */
WorkoutLog.prototype.sets = undefined;

/**
 * @member {Number} reps
 */
WorkoutLog.prototype.reps = undefined;

