/*
 * Fitness Tracker API
 * API documentation for the Fitness Tracker Web Application
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.54
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FitnessTrackerApi);
  }
}(this, function(expect, FitnessTrackerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WorkoutLog', function() {
      beforeEach(function() {
        instance = new FitnessTrackerApi.WorkoutLog();
      });

      it('should create an instance of WorkoutLog', function() {
        // TODO: update the code to test WorkoutLog
        expect(instance).to.be.a(FitnessTrackerApi.WorkoutLog);
      });

      it('should have the property exerciseType (base name: "exerciseType")', function() {
        // TODO: update the code to test the property exerciseType
        expect(instance).to.have.property('exerciseType');
        // expect(instance.exerciseType).to.be(expectedValueLiteral);
      });

      it('should have the property duration (base name: "duration")', function() {
        // TODO: update the code to test the property duration
        expect(instance).to.have.property('duration');
        // expect(instance.duration).to.be(expectedValueLiteral);
      });

      it('should have the property distance (base name: "distance")', function() {
        // TODO: update the code to test the property distance
        expect(instance).to.have.property('distance');
        // expect(instance.distance).to.be(expectedValueLiteral);
      });

      it('should have the property sets (base name: "sets")', function() {
        // TODO: update the code to test the property sets
        expect(instance).to.have.property('sets');
        // expect(instance.sets).to.be(expectedValueLiteral);
      });

      it('should have the property reps (base name: "reps")', function() {
        // TODO: update the code to test the property reps
        expect(instance).to.have.property('reps');
        // expect(instance.reps).to.be(expectedValueLiteral);
      });

    });
  });

}));
